-- Migration 31: Add ai_generated flag to messages
--
-- Safe additive migration. Existing rows default to false (treated as
-- human-sent). The AI auto-reply engine sets this to true when inserting
-- on behalf of a user with ai_auto_reply_enabled.
--
-- Used by:
--   - /admin/diagnostics/system → counts AI replies in last hour / 24h
--   - Future: per-user AI usage reports
--
-- Run once against Supabase production. Idempotent.

ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN NOT NULL DEFAULT false;

-- Partial index for fast "recent AI replies" lookups in the diagnostics endpoint.
-- Only AI messages get indexed (typically <5% of message volume).
CREATE INDEX IF NOT EXISTS idx_messages_ai_generated_created
  ON public.messages (created_at DESC)
  WHERE ai_generated = true;

COMMENT ON COLUMN public.messages.ai_generated IS
  'true when this message was generated by the AI auto-reply engine. Set by aiAutoReplyEngine.ts on insert.';
