import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import generateImageRouter from "./generateImage.js";
import generateVideoRouter from "./generateVideo.js";
import generateMultiframeVideoRouter from "./generateMultiframeVideo.js";
import presetsRouter from "./presets.js";
import sociaGptRouter from "./sociaGpt.js";
import sociaGptMemoryRouter from "./sociaGptMemory.js";
import aiPlansRouter from "./aiPlans.js";
import messagesRouter from "./messages.js";
import adminAuthRouter from "./adminAuth.js";
import adminOpsRouter  from "./adminOps.js";
import refundsRouter from "./refunds.js";
import adminRefundsRouter from "./adminRefunds.js";
import receiptsRouter from "./receipts.js";
import fundingRouter from "./funding.js";
import adminFundingRouter from "./adminFunding.js";
import usageRouter from "./usage.js";
import adminUsageRouter from "./adminUsage.js";
import refundMessagesRouter from "./refundMessages.js";
import refundNotificationsRouter from "./refundNotifications.js";
import adminReceiptsRouter  from "./adminReceipts.js";
import adminAnalyticsRouter  from "./adminAnalytics.js";
import adminAuditLogRouter   from "./adminAuditLog.js";
import adminDeviceIntelRouter from "./adminDeviceIntel.js";
import adminCorrelationRouter  from "./adminCorrelation.js";
import adminEscalationRouter   from "./adminEscalation.js";
import renderJobsRouter        from "./renderJobs.js";
import enginesRouter           from "./engines.js";
import adminRenderJobsRouter   from "./adminRenderJobs.js";
import adminDiagnosticsRouter  from "./adminDiagnostics.js";
import adminStudioModelsRouter from "./adminStudioModels.js";
import adminAnomalyRouter      from "./adminAnomaly.js";
import projectsRouter          from "./projects.js";
import voiceSynthRouter        from "./voiceSynth.js";
import exportTrailerRouter     from "./exportTrailer.js";
import aiAutoReplyRouter       from "./aiAutoReply.js";
import paymongoRouter          from "./paymongo.js";
import systemStatusRouter      from "./systemStatus.js";
import aiOpsRouter             from "./aiOps.js";
import aiGovernanceRouter      from "./aiGovernance.js";
import alertSettingsRouter       from "./alertSettings.js";
import socialPostsRouter         from "./socialPosts.js";
import userNotificationsRouter   from "./userNotifications.js";
import searchRouter              from "./search.js";
import tipRouter                 from "./tip.js";
import streamsRouter             from "./streams.js";
import starsRouter               from "./stars.js";
import pulsesRouter              from "./pulses.js";
import soundsRouter              from "./sounds.js";
import exploreRouter             from "./explore.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(generateImageRouter);
router.use(generateVideoRouter);
router.use(generateMultiframeVideoRouter);
router.use(presetsRouter);
router.use(sociaGptRouter);
router.use(sociaGptMemoryRouter);
router.use(aiPlansRouter);
router.use(messagesRouter);
router.use(adminAuthRouter);
router.use(adminOpsRouter);
router.use(refundsRouter);
router.use(receiptsRouter);
router.use(adminRefundsRouter);
router.use(fundingRouter);
router.use(adminFundingRouter);
router.use(usageRouter);
router.use(adminUsageRouter);
router.use(refundMessagesRouter);
router.use(refundNotificationsRouter);
router.use(adminReceiptsRouter);
router.use(adminAnalyticsRouter);
router.use(adminAuditLogRouter);
router.use(adminDeviceIntelRouter);
router.use(adminCorrelationRouter);
router.use(adminEscalationRouter);
router.use(renderJobsRouter);
router.use(enginesRouter);
router.use(adminRenderJobsRouter);
router.use(adminDiagnosticsRouter);
router.use(adminStudioModelsRouter);
router.use(adminAnomalyRouter);
router.use(projectsRouter);
router.use(voiceSynthRouter);
router.use(exportTrailerRouter);
router.use(aiAutoReplyRouter);
router.use(paymongoRouter);
router.use(systemStatusRouter);
router.use(aiOpsRouter);
router.use(aiGovernanceRouter);
router.use(alertSettingsRouter);
router.use(socialPostsRouter);
router.use(userNotificationsRouter);
router.use(searchRouter);
router.use(tipRouter);
router.use(streamsRouter);
router.use(starsRouter);
router.use(soundsRouter);
router.use(pulsesRouter);
router.use(exploreRouter);

export default router;
